[package]
name = "lalrpop-intern"
version = "0.12.4" # LALRPOP
description = "Simple string interner used by LALRPOP"
repository = "https://github.com/nikomatsakis/lalrpop"
license = "Apache-2.0/MIT"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
workspace = ".."
