[package]
name = "lalrpop-snap"
version = "0.10.0" # LALRPOP
description = "snapshot of LALRPOP for use in bootstrapping"
repository = "https://github.com/nikomatsakis/lalrpop"
license = "Apache-2.0/MIT"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
# build = "build.rs"

[dependencies]
regex = "0.1"
diff = "0.1"
itertools = "0.3"
unicode-xid = "0.0.2"
petgraph = "0.1.11"

[dev-dependencies]
rand = "0.3"

[dependencies.lalrpop-util]
path = "../lalrpop-util"
version = "0.10.0" # LALRPOP

[dependencies.lalrpop-intern]
path = "../lalrpop-intern"
version = "0.10.0" # LALRPOP
