[package]
name = "lexer-modes"
version = "0.1.0"
edition = "2024"
authors = ["Neal H. Walfield <neal@sequoia-pgp.org>"]
publish = false

[build-dependencies]
lalrpop = { version = "0.22.2", path = "../../lalrpop" }

[dependencies]
lalrpop-util = { version = "0.22.2", path = "../../lalrpop-util" }
