language: rust
rust:
- 1.20.0
- beta
- nightly
install:
- source ~/.cargo/env || true
- bash tools/ci-install.sh
script:
- CARGO_INCREMENTAL=0 cargo test --all
- bash tools/build-doc
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: doc/book
  on:
    branch: master
env:
  global:
    secure: Z9rnzaLlpFCX6QSiUEEKfiF9AZd+cJD13dgnz1ZpV4wqLsithvgL2TxJSXgR6nBW4HMhIyRfjsXDIEc1qlU3RRMGLX7h1lESnM1iNuLRHyBnBQKATVneLazg5/yoRo3x1Kt6iTFV4vJvIm5T0YTzkpaB9AgCcx4xErCkU3EMJMxrQzjXj0H3ASJmt+tKWZQZ+kwQQmJTVSWlWyvqDHz0EfYmdIsKjWFeT61w/OlxdlbobWf87lS1U8BSUr1b1mrsTg0VBKeeTMi+xv/MHOykgjMfjx+lIIpzZI0ie+C4LFYOOun5V6P8g4mzNlvPV0B5c5XKVEIWJhhE4oobYOXBmLy9YFcW9EsKpuoDtzFCyiD25sD6m25EZ+6eNg/lY130m/wyPPIghu43kNbuAB1XzFxIFpGzYGFfTMT04aEp/DDm1pCOG26uzyWktYf4cEUDTJKuliBfOrGZ3IcvBRemgiQsJA4s5Gz0BgMTYpxVH9bu74ebXoMeit88S2NFcfSl8gKHxvmhhLO8eRt5yrhdcBJ3GkVbJgqT8OqZSbpPqUYn3+uOIF+kqSn4jCH0pK3ckYLFKZTyTKQ9nKuw3rgu3oj0+mqyz3Hsiz7B78dR73Iq332CB382I2M+LtlUPjck0CBqD7IWa3Y9MjE9ucdJLEDIQp//vSZVvJaGnrIexnQ=
