[package]
name = "pascal"
version = "0.11.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
build = "build.rs"

[build-dependencies.lalrpop]
path = "../../../lalrpop"

[dependencies]
docopt = "0.7"
rustc-serialize = "0.3"
regex = "0.2.1"

[dependencies.lalrpop-util]
version = "0.13.0"
path = "../../../lalrpop-util"
