[package]
name = "whitespace"
version = "0.15.2"
authors = ["Mako <jlauve@rsmw.net>"]
build = "build.rs"

[build-dependencies.lalrpop]
version = "0.15.2"
path = "../../lalrpop"

[dependencies.lalrpop-util]
version = "0.15.2"
path = "../../lalrpop-util"
