[package]
name = "whitespace"
version = "0.19.9"
authors = ["Mako <jlauve@rsmw.net>"]
build = "build.rs"
edition = "2018"

[build-dependencies.lalrpop]
version = "0.19.9"
path = "../../lalrpop"

[dependencies.lalrpop-util]
version = "0.19.9"
path = "../../lalrpop-util"
