[package]
name = "whitespace"
version = "0.22.2"
authors = ["Mako <jlauve@rsmw.net>"]
edition = "2024"
publish = false

[build-dependencies.lalrpop]
version = "0.22.2"
path = "../../lalrpop"

[dependencies.lalrpop-util]
version = "0.22.2"
path = "../../lalrpop-util"
