[package]
name = "lalrpop-test"
version = "0.12.0" # LALRPOP
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
license = "Apache-2.0/MIT"
build = "build.rs"
workspace = ".."

[dependencies]
diff = "0.1"

[dependencies.lalrpop-util]
path = "../lalrpop-util"

[build-dependencies.lalrpop]
path = "../lalrpop"

