[package]
name = "lalrpop-test"
version = "0.18.1" # LALRPOP
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
license = "Apache-2.0/MIT"
build = "build.rs"
workspace = ".."

[dependencies]
diff = "0.1.12"
regex = "1"

[dependencies.lalrpop-util]
path = "../lalrpop-util"

[build-dependencies.lalrpop]
path = "../lalrpop"
features = ["lexer"]


[features]
default = ["test-set"]
test-set = []
