name: Test book

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  lint-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.52'

      - name: Install mdbook-linkcheck
        run: |
          curl -Ls https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/latest/download/mdbook-linkcheck.x86_64-unknown-linux-gnu.zip -o mdbook-linkcheck.zip &&
          unzip -n "$_" mdbook-linkcheck &&
          chmod +x "$_"
        working-directory: ./doc

      - name: Lint book
        run: |
          sudo gem install mdl
          mdl doc

      - run: env PATH=$PWD:$PATH mdbook build
        working-directory: ./doc
